// <auto-generated />
using System;
using System.Collections.Generic;
using DogRaces.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DogRaces.Infrastructure.Migrations
{
    [DbContext(typeof(DogRacesContext))]
    [Migration("20250830221552_UpdateTableNamesToSnakeCase")]
    partial class UpdateTableNamesToSnakeCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DogRaces.Domain.Entities.Bet", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BetType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsWinning")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Odds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("RaceId")
                        .HasColumnType("bigint");

                    b.Property<int>("Selection")
                        .HasColumnType("integer");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.HasIndex("TicketId");

                    b.ToTable("bets", (string)null);
                });

            modelBuilder.Entity("DogRaces.Domain.Entities.GlobalConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MaxTicketWin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(10000.00m)
                        .HasColumnName("max_ticket_win");

                    b.Property<int>("MinNumberOfActiveRounds")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(7)
                        .HasColumnName("min_number_of_active_rounds");

                    b.Property<decimal>("MinTicketStake")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(1.00m)
                        .HasColumnName("min_ticket_stake");

                    b.HasKey("Id");

                    b.ToTable("global_configuration", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxTicketWin = 10000.00m,
                            MinNumberOfActiveRounds = 7,
                            MinTicketStake = 1.00m
                        });
                });

            modelBuilder.Entity("DogRaces.Domain.Entities.Race", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("RaceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<int>>("RandomNumbers")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ResultDeterminedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ResultPublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("races", (string)null);
                });

            modelBuilder.Entity("DogRaces.Domain.Entities.RaceOdds", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Odds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("RaceId")
                        .HasColumnType("bigint");

                    b.Property<int>("Selection")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RaceId", "Selection")
                        .IsUnique();

                    b.ToTable("race_odds", (string)null);
                });

            modelBuilder.Entity("DogRaces.Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("TotalPayout")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalStake")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("DogRaces.Domain.Entities.Bet", b =>
                {
                    b.HasOne("DogRaces.Domain.Entities.Race", "Race")
                        .WithMany("Bets")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DogRaces.Domain.Entities.Ticket", "Ticket")
                        .WithMany("Bets")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("DogRaces.Domain.Entities.RaceOdds", b =>
                {
                    b.HasOne("DogRaces.Domain.Entities.Race", "Race")
                        .WithMany("RaceOdds")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("DogRaces.Domain.Entities.Race", b =>
                {
                    b.Navigation("Bets");

                    b.Navigation("RaceOdds");
                });

            modelBuilder.Entity("DogRaces.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("Bets");
                });
#pragma warning restore 612, 618
        }
    }
}
